{
 "title": "WAZUH - OVERVIEW (Grafana)",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "agent_name",
    "label": "Agent",
    "query": "{ \"find\": \"terms\", \"field\": \"agent.name\", \"query\": \"\"}"
   },
   {
    "name": "rule_level",
    "label": "Rule Level",
    "query": "{ \"find\": \"terms\", \"field\": \"rule.level\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "EVENTS (TOTAL)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:331",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:329", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule.level:>=12 AND agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "MAX SEVERITY (0 - 15)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "rule.level",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS - DETAILS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "250" }, "type": "logs" }
     ],
     "query": "agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "AGENTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "365d", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "agent.name",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY CATEGORY GROUP",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:332",
       "field": "rule.groups",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:330",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY CATEGORY",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "rule.groups",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule.level:>=12 AND agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "SECURITY EVENTS BY ALERT LEVEL",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "fake": true,
       "field": "rule.level",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:236",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS BY AGENT (TOP 10)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:235",
       "fake": true,
       "field": "agent.name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:236",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:233",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "ALERTS BY AGENT",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "agent.name",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "rule.level:>=12 AND agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS SEVERITY - HISTOGRAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule.level",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "agent.name:$agent_name",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "EVENTS",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "250" }, "type": "raw_data" }
     ],
     "query": "agent.name:$agent_name AND rule.level:$rule_level",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}